### PR TITLE
Use gzweb2 to render Model and Worlds

### PR DESCRIPTION
**Pull request by german-e-mas**
This PR uses the latest changes on Gzweb (2.0.13) in order to render Models and Worlds. The SDF Viewer Component has been modified to use the new gzweb's AssetViewer, which tries to handle much of the logic the SDF Viewer Component used to have.

Another change includes getting rid of the `Detector` module, which was part of the previous Gzweb version. It was used to detect if the browser can create a WebGL context. We use a method [that ThreeJS uses](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/capabilities/WebGL), but avoiding the dependency.

---

## Notes:
- ~~The lightning is slightly off from gzweb v1 to v2. See [gzweb's PR](https://github.com/gazebo-web/gzweb/pull/50).~~ Fixed at [this Gzweb PR](https://github.com/gazebo-web/gzweb/pull/54)
- ~~The version of gzweb is not yet increased. In order to test this PR, you can download the changes of gzweb and locally install the dependency (`npm i <PathToGzweb>`)~~

Can you ptal @nkoenig ?

## Some comparisons (see the lightning differences)

Note: The differences are fixed at https://github.com/gazebo-web/gzweb/pull/54

| gzweb v1 | gzweb v2 |
| --- | --- |
| staging-app gazebosim org_OpenRobotics_fuel_worlds_Cave%20Circuit%2001 | localhost_3000_OpenRobotics_fuel_worlds_Cave%20Simple%2003 |
| staging-app gazebosim org_gmas_fuel_models_Urban%20Stairwell%20Platform%20Centered%20Lights | localhost_3000_gmas_fuel_models_Urban%20Stairwell%20Platform%20Centered%20Lights |

### CODE REVIEW

**Comment by nkoenig** [comment]
I see this error when running `npm start`

```
./src/app/model/sdfviewer/sdfviewer.component.ts:76:27-38 - Error: export 'AssetViewer' (imported as 'AssetViewer') was not found in 'gzweb' (possible exports: Asset, AudioTopic, Color, FuelServer, Gamepad, Inertia, Material, ModelUserData, PBRMaterial, Pose, Publisher, SDFParser, Scene, SceneManager, SceneManagerConfig, Topic, Transport, binaryToBase64, binaryToImage, getDescendants)
```

**Comment by nkoenig** [comment]
Do you see this console error when trying to visualize a model in 3d: 
```
core.mjs:9171 ERROR Error: NG0302: The pipe 'async' could not be found in the 'SdfViewerComponent' component. Verify that it is included in the '@Component.imports' of this component.
```
Also, the 3d visualization doesn't work for me.

**Comment by german-e-mas** [comment]
> Do you see this console error when trying to visualize a model in 3d:
> 
> ```
> core.mjs:9171 ERROR Error: NG0302: The pipe 'async' could not be found in the 'SdfViewerComponent' component. Verify that it is included in the '@Component.imports' of this component.
> ```
> 
> Also, the 3d visualization doesn't work for me.

That's interesting. Given the error, looks like the compiler is seeing the SDF Viewer component as a standalone one, which isn't in this PR. I'll take a closer look.

**Comment by german-e-mas** [comment]
> Do you see this console error when trying to visualize a model in 3d:
> 
> ```
> core.mjs:9171 ERROR Error: NG0302: The pipe 'async' could not be found in the 'SdfViewerComponent' component. Verify that it is included in the '@Component.imports' of this component.
> ```
> 
> Also, the 3d visualization doesn't work for me.

This error is not happening to me. Make sure you checkout this branch and are not working in a branch with standalone components, which may cause issues.

You will need the latest changes of Gzweb, which are not included in the PR (we need to release first). So make sure you pull the latest gzweb changes, build them (`npm run build` in `gzweb`) and then install them (`npm i path/to/gzweb` at the root of the gazebo app)

**Comment by german-e-mas** [comment]
The differences in lightning and colors are fixed at https://github.com/gazebo-web/gzweb/pull/54

**Comment by nkoenig** [comment]
I must have had some crud leftover in my workspace.  A fresh checkout and build works fine.

**Review by nkoenig — APPROVED** [review]

**Pull request merged**
